#!/usr/bin/env bash
#function and bash script
myfunc () {
    dns=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $dns" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}


if [ "$#" == 1 ];then
    myfunc "$1" "www"
    myfunc "$1" "lb-01"
    myfunc "$1" "web-01"
    myfunc "$1" "web-02"
elif [ "$#" == 2 ];then
    myfunc "$1" "$2"
fi
