#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server:

if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
  ssh_opt="-o StrictHostKeyCheking=no"
  scp $ssh_opt -i "$4" "$1" "$3@$2":~
fi
