#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
server {
        listen 80 ;
        listen [::]:80 ;


        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        #location / {
         #       try_files $uri $uri/ =404;
        #}
        location  / {
	        echo "Hello World";
	}
}
