#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx start
