#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get -y  update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
con="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$con/" /etc/nginx/sites-enabled/default
sudo service nginx restart 
