#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee  /var/www/html/index.html

redirect_con="erver {
  listen 80;
  listen [::]80;
  server_name _;

  location /redirect_me{
  return 301 http://carterm5.tech/ permanent;
}"
sudo sed -i '/server {/c\'"$redirect_con" /etc/nginx/sites-enabled/default

service nginx restart
