#!/usr/bin/env bash
#Bash script that configures a 404
sudo apt-get -y  update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sh -c 'echo "<h1>Ceci n'est pas une page</h1>" > /var/www/html/404.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation \/ {error_page 404 /404.html;}' /etc/nginx/sites-available/default

sudo service nginx start
~                        
