#!/usr/bin/env bash
#Bash script that configures a 404
sudo apt-get -y  update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -r 755 /var/www
echo "Hello World" | sudo tee /var/www/html/index.html
con="server_name _;i\n\tadd_header X-Served-By \$hostname\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$con/" /etc/nginx/sites-enabled/default


echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$error/" /etc/nginx/sites-enabled/default
sudo service nginx restart
