#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo echo "Holberton School" > /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i 's/server_name _;/&\n\trewrite ^\/redirect_me http:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/g' /etc/nginx/sites-available/default

sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
sudo service nginx restart
