#!/usr/bin/env bash
#traps

file=/var/run/myscript.pid
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT
echo $$ > '$file'
while true; do
	echo "To infinity and beyond"
	sleep 2
done
