#!/usr/bin/env bash
#ifs

while IFS=: read -r USERNAME, PASSWORD, GROUP_ID, USER_ID, HOME_DIRECTORY, COMMAND_SHELL;do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID"
done

