#!/usr/bin/env bash
#a while loop to display best school 10 times

myvar=1
while [ $myvar -le 20 ]
do
	case $myvar in 4)
                echo -e "$myvar\nbad luck from China"
		;;
	9)
                echo -e "$myvar\nbad luck from Japan"
		;;
	17)
		echo -e "$myvar\nbad luck from Italy"
		;;
	*)
		echo $myvar
	esac
        myvar=$((myvar + 1))
done
